# Generated by Django 3.2.1 on 2021-05-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('isbn', models.IntegerField(max_length=13)),
                ('autor', models.CharField(max_length=70)),
                ('editora', models.CharField(max_length=70)),
                ('edição', models.IntegerField(max_length=6)),
                ('numero_de_pgs', models.IntegerField(max_length=4)),
                ('descrição', models.TextField(max_length=300)),
            ],
        ),
    ]
