# Generated by Django 3.2.1 on 2021-05-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMDb_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='edição',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livros',
            name='isbn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livros',
            name='numero_de_pgs',
            field=models.IntegerField(),
        ),
    ]
